version: '3.7'
services:
  Web:
    image: abiosoft/caddy
    ports:
      - 80:80
    volumes:
      - './Caddyfile:/etc/Caddyfile'
  api:
    build:
      context: './API'
      dockerfile: 'Dockerfile.dev'
    image: 'applicationtemplate'
    environment:
      DB_HOST: database
      DB_PASSWORD: pgpass
    volumes:
      - './API:/development'
  ui:
    build:
      context: './Web'
      dockerfile: 'Dockerfile.dev'
    image: 'applicationtemplateweb'
    volumes:
      - './Web:/development'
  database:
    image: postgres:11-alpine
    volumes:
      - databaseData:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: application
volumes:
  databaseData: