version: '3.7'
services:
  Web:
    image: docker.pkg.github.com/kristianfjones/docker-images/caddy2:alpine
    command: ['run', '--config', '/etc/Caddy/Caddyfile.json']
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./Caddyfile.json:/etc/Caddy/Caddyfile.json

  API:
    build:
      context: './API'
      dockerfile: 'Dockerfile.dev'
    image: 'applicationtemplate'
    environment:
      DB_HOST: database
      DB_PASSWORD: pgpass
    volumes:
      - './API:/development'
      - './API.graphql:/API.graphql'

  Web-gen:
    build:
      context: './Scripts/GraphQLCodegen'
      dockerfile: 'Dockerfile'
    image: 'applicationtemplate-gen'
    volumes:
      - './Web:/data'

  Web-UI:
    build:
      context: './Web'
      dockerfile: 'Dockerfile.dev'
    image: 'applicationtemplate-web'
    environment:
      API_HOST: api
      PUBLIC_URL: http://localhost
    ports:
      - 5859:5859
    volumes:
      - './Web:/development'

  Database:
    image: postgres:11-alpine
    volumes:
      - databaseData:/var/lib/postgresql/data
    ports:
      - 4763:5432
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: application

volumes:
  databaseData:
