name: Publish API Docker image
on:
  push:
    branches:
      - master
    paths:
      - 'API/*'
      - 'API/*/*'
      - 'API/*/*/*'
      - 'API/*/*/*/*'
      - 'API/*/*/*/*/*'
      - 'API/*/*/*/*/*/*'
      - 'API/*/*/*/*/*/*/*'
      - 'API/*/*/*/*/*/*/*/*'
      - 'API/*/*/*/*/*/*/*/*/*'
      - 'API/*/*/*/*/*/*/*/*/*/*'
      - '.github/workflows/Build-API.yml'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: textbook/git-checkout-submodule-action@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: API/Dockerfile
          name: docker.pkg.github.com/kristianfjones/application-template/application-template-api
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: API
