name: Code Quality
on: pull_request

jobs:
  Test:
    name: Testing
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pgpass
          POSTGRES_HOST: localhost
          POSTGRES_DB: application
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - uses: KristianFJones/npm-run-action@master
        env:
          DB_HOST: postgres
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          scriptName: "test"
  Prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: KristianFJones/npm-run-action@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          scriptName: "prettier"
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: KristianFJones/npm-run-action@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          scriptName: "lint"